package MakeAss;

use strict;
use warnings;

use Data::Dumper;
use POSIX;

use Encode; #help avoid wide print errors
use utf8;

sub writeass
{
  my $tmp = shift;
  my @codes = @_;

  open(my $fh, ">:encoding(utf8)", sprintf("%s/output.ass", $tmp));
  print $fh <DATA>;
  close($fh);
}

__DATA__
﻿[Script Info]
; Script generated by Autosub 0.0.1 alpha
Title: Default Autosub File
ScriptType: v4.00+
WrapStyle: 0
;i should get these correctly, oh well
PlayResX: 640
PlayResY: 480
ScaledBorderAndShadow: yes
Video Aspect Ratio: 0
Video Zoom: 8
Video Position: 4882
;Audio File: audiodump.wav
;Video File: DC215.avi

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
;Dialogue: 0,0:00:19.40,0:00:21.14,Default,,0000,0000,0000,,A courageous heart and deduction power!
